name: nyanya_rocket_cloud_server
description: NyaNya Rocket! dedicated game server.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  nyanya_rocket_base:
    git:
      url: git://github.com/CaramelDunes/nyanya_rocket_base.git
      ref: feature/nnbd

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.6
