name: nyanya_rocket_cloud_server
description: NyaNya Rocket! dedicated game server.

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  nyanya_rocket_base:
    git:
      url: git://github.com/CaramelDunes/nyanya_rocket_base.git

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
